# Generated by Django 5.0.1 on 2026-01-06 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credor", models.CharField(max_length=200, verbose_name="Credor")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "numero_parcelas",
                    models.IntegerField(verbose_name="Número de Parcelas"),
                ),
                (
                    "parcelas_pagas",
                    models.IntegerField(default=0, verbose_name="Parcelas Pagas"),
                ),
                (
                    "taxa_juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Taxa de juros mensal em percentual",
                        max_digits=5,
                        verbose_name="Taxa de Juros (%)",
                    ),
                ),
                ("data_contratacao", models.DateField(verbose_name="Data Contratação")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empréstimo",
                "verbose_name_plural": "Empréstimos",
                "db_table": "Emprestimo",
                "ordering": ["-data_contratacao"],
            },
        ),
    ]
