# Generated by Django 5.0.1 on 2026-01-06 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Provento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[("cpf", "CPF"), ("cnpj", "CNPJ")],
                        max_length=4,
                        verbose_name="Tipo Pessoa",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("data_recebimento", models.DateField(verbose_name="Data Recebimento")),
                ("mes_referencia", models.DateField(verbose_name="Mês Referência")),
                (
                    "recebido",
                    models.BooleanField(default=False, verbose_name="Recebido"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proventos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provento",
                "verbose_name_plural": "Proventos",
                "db_table": "Provento",
                "ordering": ["-data_recebimento"],
            },
        ),
    ]
