# Generated by Django 5.0.1 on 2026-01-06 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cartoes", "0001_initial"),
        ("categorias", "0001_initial"),
        ("emprestimos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeioPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("pix", "PIX"),
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferência"),
                            ("boleto", "Boleto"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meios_pagamento",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meio de Pagamento",
                "verbose_name_plural": "Meios de Pagamento",
                "db_table": "MeioPagamento",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "local",
                    models.CharField(blank=True, max_length=200, verbose_name="Local"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "parcelado",
                    models.BooleanField(default=False, verbose_name="Parcelado"),
                ),
                (
                    "numero_parcelas",
                    models.IntegerField(default=1, verbose_name="Número de Parcelas"),
                ),
                (
                    "parcela_atual",
                    models.IntegerField(default=1, verbose_name="Parcela Atual"),
                ),
                ("data_gasto", models.DateField(verbose_name="Data do Gasto")),
                ("pago", models.BooleanField(default=False, verbose_name="Pago")),
                ("mes_referencia", models.DateField(verbose_name="Mês Referência")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "cartao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gastos",
                        to="cartoes.cartao",
                        verbose_name="Cartão",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="categorias.categoria",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "emprestimo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gastos",
                        to="emprestimos.emprestimo",
                        verbose_name="Empréstimo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gastos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "meio_pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="gastos.meiopagamento",
                        verbose_name="Meio de Pagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "db_table": "Gasto",
                "ordering": ["-data_gasto"],
            },
        ),
    ]
