# Generated by Django 5.0.1 on 2026-01-06 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cartao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "bandeira",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("elo", "Elo"),
                            ("amex", "American Express"),
                            ("hipercard", "Hipercard"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Bandeira",
                    ),
                ),
                (
                    "limite",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Limite"
                    ),
                ),
                (
                    "dia_vencimento",
                    models.IntegerField(
                        help_text="Dia do mês (1-31)", verbose_name="Dia Vencimento"
                    ),
                ),
                (
                    "dia_fechamento",
                    models.IntegerField(
                        help_text="Dia do mês (1-31)", verbose_name="Dia Fechamento"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartão",
                "verbose_name_plural": "Cartões",
                "db_table": "Cartao",
                "ordering": ["nome"],
            },
        ),
    ]
